on:
  push:
    branches:
      -master
      






jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'print folder'
        run: pwd

      - name: 'print folder'
        run: echo fatma
        

     
    



